# Generated by Django 5.1.1 on 2024-10-05 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brang',
            new_name='brand',
        ),
    ]
